apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
	# Add TLS / auth / rewrite annotations as needed
spec:
  ingressClassName: <> #nginx-example
  rules:
  - http:
      paths:
      - path: <> /testpath
        pathType: Prefix
        backend:
          service:
            name: <>
            port:
              number: <>
	        - path: <> /testpath
      - pathType: Prefix
        backend:
          service:
            name: mysvc
            port:
              number: <>
