apiVersion: v1
kind: Service
metadata:
  name: mysvc
  labels:
    app: flaskapp
spec:
  type: ClusterIP
  selector:
    app: flaskapp
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
