name: Deploy to EKS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
         aws-access-key-id: ${{ secrets.ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.SECRET_KEY }}
         aws-region: us-east-1

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name myekscluster --region us-east-1

      - name: Test kubernetes cluster and nodes are created or not
        run: kubectl get nodes

      # - name: Apply Kubernetes manifests
      #   run: |
      #     kubectl apply -f k8s-manifests/deployment.yaml
      #     kubectl apply -f k8s-manifests/service.yaml
      # #     kubectl apply -f k8s-manifests/ingress.yaml
      - name: alb controller install
        run: |
          curl -O https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.13.3/docs/install/iam_policy.json
          
          aws iam create-policy \
          --policy-name AWSLoadBalancerControllerIAMPolicy \
          --policy-document file://iam_policy.json
	
          eksctl create iamserviceaccount \
          --cluster=myekscluster \
          --namespace=kube-system \
          --name=aws-load-balancer-controller \
          --attach-policy-arn=arn:aws:iam::561947681169:policy/AWSLoadBalancerControllerIAMPolicy \
          --override-existing-serviceaccounts \
          --region us-east-1 \
          --approve
	
          helm repo add eks https://aws.github.io/eks-charts

          helm repo update eks

          helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
          -n kube-system \
          --set clusterName=myekscluster \
          --set serviceAccount.create=false \
          --set serviceAccount.name=aws-load-balancer-controller \
          --version 1.13.0
  
      - name: Verify ingress Alb controller is installed or not
        run: kubectl get deployment -n kube-system aws-load-balancer-controller