name: Deploy to EKS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
         aws-access-key-id: ${{ secrets.ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.SECRET_KEY }}
         region: us-east-1

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: '1.28.0'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name demo-eks-cluster --region ap-south-1

      - name: Test kubernetes cluster and nodes are created or not
        run: kubectl get nodes

      # - name: Apply Kubernetes manifests
      #   run: |
      #     kubectl apply -f k8s-manifests/deployment.yaml
      #     kubectl apply -f k8s-manifests/service.yaml
      #     kubectl apply -f k8s-manifests/ingress.yaml
